package uy.edu.fing.tse.client.dnic;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-11-11T23:11:39.769-03:00
 * Generated source version: 4.1.3
 *
 */
@WebService(targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic", name = "DnicPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DnicPort {

    @WebMethod(operationName = "ObtPersonaPorDoc")
    @WebResult(name = "ObtPersonaPorDocResponse", targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic", partName = "ObtPersonaPorDocResponse")
    public ObtPersonaPorDocResponse obtPersonaPorDoc(

        @WebParam(partName = "ObtPersonaPorDocRequest", name = "ObtPersonaPorDocRequest", targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic")
        ObtPersonaPorDocRequest obtPersonaPorDocRequest
    );

    @WebMethod(operationName = "ProductDesc")
    @WebResult(name = "ProductDescResponse", targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic", partName = "ProductDescResponse")
    public ProductDescResponse productDesc(

        @WebParam(partName = "ProductDescRequest", name = "ProductDescRequest", targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic")
        ProductDescRequest productDescRequest
    );
}
