package uy.edu.fing.tse.client.dnic;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-11-11T23:11:39.817-03:00
 * Generated source version: 4.1.3
 *
 */
@WebServiceClient(name = "DnicPortService",
                  wsdlLocation = "https://env-3816318.web.elasticloud.uy/ws/dnic.wsdl",
                  targetNamespace = "http://agesic.gub.uy/pdi/ws/dnic")
public class DnicPortService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://agesic.gub.uy/pdi/ws/dnic", "DnicPortService");
    public static final QName DnicPortSoap11 = new QName("http://agesic.gub.uy/pdi/ws/dnic", "DnicPortSoap11");
    static {
        URL url = null;
        try {
            url = URI.create("https://env-3816318.web.elasticloud.uy/ws/dnic.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DnicPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://env-3816318.web.elasticloud.uy/ws/dnic.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DnicPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DnicPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DnicPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DnicPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DnicPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DnicPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DnicPort
     */
    @WebEndpoint(name = "DnicPortSoap11")
    public DnicPort getDnicPortSoap11() {
        return super.getPort(DnicPortSoap11, DnicPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DnicPort
     */
    @WebEndpoint(name = "DnicPortSoap11")
    public DnicPort getDnicPortSoap11(WebServiceFeature... features) {
        return super.getPort(DnicPortSoap11, DnicPort.class, features);
    }

}
